In [1]:
####The main program file
import pandas as pd
import os
import numpy as np

In [3]:
#CALLLING OUT CSV FILE LOCATIONS
SoCo_path_1 = os.path.join(".", "Resources","SoCo-Animal_Shelter_Intake_and_Outcome.csv")

# READING CSV DATA INTO DATA FRAMES
SoCo_df = pd.read_csv(SoCo_path_1)

#CHECKING DATA FRAME HEADS TO ENSURE DATA IS BEING CORRECLTY READ
SoCo_df.head()

,Name,Type,Breed,Color,Sex,Size,Date Of Birth,Impound Number,Kennel Number,Animal ID,...,Intake Subtype,Outcome Type,Outcome Subtype,Intake Condition,Outcome Condition,Intake Jurisdiction,Outcome Jurisdiction,Outcome Zip Code,Location,Count
0,SKY,DOG,GERM SHEPHERD,BLACK/TAN,Female,MED,NaN,K20-035118,DS69,A395686,...,FIELD,RETURN TO OWNER,OVER THE COUNTER_CALL,HEALTHY,HEALTHY,COUNTY,COUNTY,95404.0,"95404(38.458384, -122.675588)",1
1,COCO,DOG,BEAGLE,TRICOLOR,Neutered,SMALL,04/06/2015,K17-025093,DS83,A379968,...,FIELD,TRANSFER,NC AN FRND,UNKNOWN,HEALTHY,SANTA ROSA,OUT OF COUNTY,95758.0,"95758(38.424655, -121.438065)",1
2,SUZIE,DOG,LABRADOR RETR/MIX,BLACK,Spayed,LARGE,01/23/2011,K15-012348,DA34,A315553,...,OVER THE COUNTER,ADOPTION,INTERNET,HEALTHY,HEALTHY,SANTA ROSA,SANTA ROSA,95404.0,"95404(38.458384, -122.675588)",1
3,NaN,DOG,GERM SHEPHERD/MIX,TRICOLOR,Unknown,MED,NaN,K20-036188,VET,A398868,...,FLD_CRUEL,RETURN TO OWNER,MEDICAL,UNKNOWN,HEALTHY,SANTA ROSA,NaN,NaN,NaN,1
4,FELIX,CAT,DOMESTIC SH,BLACK,Neutered,KITTN,05/12/2018,K18-029084,LOBBY,A374683,...,OVER THE COUNTER,ADOPTION,WALKIN,HEALTHY,HEALTHY,SANTA ROSA,COUNTY,95407.0,"95407(38.403734, -122.736775)",1